dist: trusty
language: generic

jobs:
  include:
    - stage: build docker image
      script:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/$1.29.1/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - stage: test api
      script:
    - docker-compose -f docker-compose.test-api.yml up --build --exit-code-from api-test
    - stage: test client
      script:
    - docker-compose -f docker-compose.test-client.yml up --build --exit-code-from client-test