version: "3.3"

services:
    client-test:
        build: ./client
        ports:
            - 8080:8080
        volumes:
            - ./client:/client
        command: bash -c "yarn && quasar test --unit jest"