version: "3.3"

services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        env_file: .env

    api:
        build: ./api
        ports:
            - 8000:8000
        volumes:
            - ./api:/api
        command: ["sh", "start.sh"]
        env_file: .env
        restart: on-failure
        depends_on:
            - db